<div style="font-family: Arial, Helvetica, sans-serif; font-size: 14px; padding: 10px; line-height: 1.5;">
	<?php echo $this->bodyMessage;?>
	--------------------------------------------
	<p style="font-size:12px"><em>
	Contacte: MD-2005 mun.Chisinau str.Puskin 28 tel: (+373 22) 819-819 office@gamaavia.md Manager- S. CAROLINA Ore de lucru: Luni-vineri: 9:00-18:00 Simbata: 09:00-15:00, Duminica: zi de odihna<br />
	Te rugam nu raspunde la acest mesaj pentru ca a fost trimis de la o adresa nemonitorizata. /
	Просим вас не отвечать на это письмо ибо было послоно с неконтролируемого адресса.<br />
	<font color="red">Daca nu vrei sa mai primesti mesaje de la noi te poti dezabona dand click pe linkul de mai jos /Чтобы отписаться следуй по ссылке ниже</font><br />
	<?php echo $this->fullUrl;?>/user/unsubscribe/email/<?php echo $this->encodedMail;?>
	</em></p>
</div>